apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: studio-db
    name: studio-db
  name: studio-db
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-studio-db
  template:
    metadata:
      labels:
        io.kompose.service: studio-db
        name: {{ .Release.Name }}-studio-db
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db.name }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.db.password }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.db.user }}
        image: postgres
        name: studio-db
        resources: {}
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-studio-db-pvc
status: {}
